[versions]
ij-gradle-plugin = "2.6.0"
ij-rpc-plugin = "2.1.10-0.2"
ij-kotlin-jvm-plugin = "2.1.10"
ij-kotlin-serialization-plugin = "2.1.10"
ij-platform = "2025.1"

[plugins]
#rpc-gradle-plugin = { module = "rpc:rpc.gradle.plugin", version.ref = "ij-rpc-plugin" }
#kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "ij-kotlin-jvm-plugin" }
#kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "ij-kotlin-serialization-plugin" }
ijPlatformGradlePlugin = { id = "org.jetbrains.intellij.platform", version.ref = "ij-gradle-plugin" }
ijRpcPlugin = { id = "rpc.gradle.plugin", version.ref = "ij-rpc-plugin" }
ij-kotlin-jvm-plugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "ij-kotlin-jvm-plugin" }
ij-kotlin-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "ij-kotlin-serialization-plugin" }
